[platformio]
default_envs = esp32s3_devkitc1_ads1299
src_dir = main

[env:esp32s3_devkitc1_ads1299]
platform = platformio/espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
