[platformio]
src_dir = examples/stm32cube_reference

[env:stm32f407g_disc1_ads1299]
platform = ststm32
board = disco_f407vg
framework = stm32cube
lib_deps =
    file://../../../core_driver/ads1299
    file://ads1299_port
    file://stm32cube_adapter
build_flags =
    -D USE_HAL_DRIVER
    -D STM32F407xx
    -Wall
    -Wextra
build_src_flags =
    -Wall
    -Wextra
    -Werror
