[platformio]
default_envs = black_f407ve

[env:black_f407ve]
platform = ststm32
board = black_f407ve
framework = stm32cube
monitor_speed = 921600
lib_ldf_mode = deep+
lib_extra_dirs =
    ../../../core_driver
    ../../../common
build_flags =
    -Iinclude
    -DADS1299_REFERENCE_PROJECT=1
    -Wall
    -Wextra
