[platformio]
default_envs = esp32c6_reference
src_dir = main
build_dir = tests/.tools/build

[env:esp32c6_reference]
platform = platformio/espressif32@6.10.0
board = esp32-c6-devkitc-1
framework = espidf
extra_scripts = pre:tests/windows_ldgen.py
monitor_speed = 115200
