[env:gd32f450z_eval]
platform = https://github.com/CommunityGD32Cores/platform-gd32.git#b80521168db1afc6e59cab59ce0685014e0a8111
board = genericGD32F450ZK
framework = spl
extra_scripts = pre:extra_sources.py
build_flags =
    -Wall
    -Wextra
    -Werror
    -DADS1299_GD32F450_REFERENCE=1
monitor_speed = 500000
