#ifndef ADS1299_STM32C031_BOARD_CONFIG_H
#define ADS1299_STM32C031_BOARD_CONFIG_H

/*
 * STM32C031 ADS1299 board configuration
 *
 * This is the single board-specific configuration header for the beginner
 * path. Keep ADS1299 register/profile logic out of this file.
 *
 * CubeMX/CubeIDE setup expected by this template:
 *   - Configure one SPI peripheral as master, full duplex, 8-bit,
 *     MSB first, CPOL=Low, CPHA=2Edge (ADS1299 SPI Mode 1).
 *   - Label GPIO outputs exactly:
 *       ADS1299_CS, ADS1299_RESET, ADS1299_PWDN, ADS1299_START
 *   - Label the active-low input exactly:
 *       ADS1299_DRDY
 *   - Generate the vendor project so main.h contains the *_Pin and
 *     *_GPIO_Port symbols for those labels.
 *
 * The default handle names below match the common CubeMX names. Change only
 * these handle aliases when your generated project uses different instances.
 */

#define ADS1299_BOARD_SPI_HANDLE          hspi1

/* Optional beginner stream transport. Leave disabled if the example only
 * prints through another application-owned logger. */
#define ADS1299_BOARD_USE_UART_STREAM     1
#define ADS1299_BOARD_UART_HANDLE         huart1

/* GPIO aliases generated by CubeMX from the required user labels. */
#define ADS1299_BOARD_CS_GPIO_PORT        ADS1299_CS_GPIO_Port
#define ADS1299_BOARD_CS_PIN              ADS1299_CS_Pin
#define ADS1299_BOARD_RESET_GPIO_PORT     ADS1299_RESET_GPIO_Port
#define ADS1299_BOARD_RESET_PIN           ADS1299_RESET_Pin
#define ADS1299_BOARD_PWDN_GPIO_PORT      ADS1299_PWDN_GPIO_Port
#define ADS1299_BOARD_PWDN_PIN            ADS1299_PWDN_Pin
#define ADS1299_BOARD_START_GPIO_PORT     ADS1299_START_GPIO_Port
#define ADS1299_BOARD_START_PIN           ADS1299_START_Pin
#define ADS1299_BOARD_DRDY_GPIO_PORT      ADS1299_DRDY_GPIO_Port
#define ADS1299_BOARD_DRDY_PIN            ADS1299_DRDY_Pin

/* Beginner-safe logical defaults. These are configuration intent, not a
 * substitute for CubeMX peripheral setup. */
#define ADS1299_BOARD_SPI_MODE            1u
#define ADS1299_BOARD_SPI_MSB_FIRST       1u
#define ADS1299_BOARD_DRDY_ACTIVE_LOW     1u
#define ADS1299_BOARD_CS_ACTIVE_LOW       1u
#define ADS1299_BOARD_RESET_ACTIVE_LOW    1u
#define ADS1299_BOARD_PWDN_ACTIVE_LOW     1u

/* Small-MCU policy: keep timing-path storage bounded and static. */
#define ADS1299_BOARD_FRAME_BYTES         27u
#define ADS1299_BOARD_STREAM_QUEUE_FRAMES 4u

#endif /* ADS1299_STM32C031_BOARD_CONFIG_H */
