/*
 * MIMXRT1189 ADS1299 board binding template.
 *
 * Copy this file into the consuming MCUXpresso board project (or compile it
 * there after replacing the TODOs). Keep ADS1299 register programming out of
 * this file: this layer only binds board peripherals/pins to the portable
 * platform HAL.
 *
 * Validation status: TEMPLATE / PLANNED. This file intentionally contains no
 * invented MIMXRT1189-EVK pin numbers or SDK handles.
 */
#include "board_ads1299.h"

#include <stddef.h>
#include <stdint.h>

/*
 * Replace the functions below with thin wrappers around the MCUXpresso SDK
 * primitives selected/generated by your board project. The opaque user pointer
 * lets a project keep its LPSPI/GPIO handles in one board-owned structure.
 */
static int board_spi_transfer(void *user, const uint8_t *tx,
                              uint8_t *rx, size_t len)
{
    (void)user;
    (void)tx;
    (void)rx;
    (void)len;
    /* TODO: bounded board-owned LPSPI transfer, SPI Mode 1/MSB first. */
    return -1;
}

static void board_pin_write(void *user, ads1299_platform_pin_t pin, int level)
{
    (void)user;
    (void)pin;
    (void)level;
    /* TODO: map CS/RESET/PWDN/START to generated MCUXpresso GPIO calls. */
}

static int board_pin_read(void *user, ads1299_platform_pin_t pin)
{
    (void)user;
    (void)pin;
    /* TODO: read ADS1299_PIN_DRDY and return its digital level. */
    return 1;
}

static void board_delay_us(void *user, uint32_t us)
{
    (void)user;
    (void)us;
    /* TODO: use the board/SDK microsecond delay primitive. */
}

int board_ads1299_hal(ads1299_platform_hal_t *hal)
{
    if (hal == NULL) {
        return -1;
    }

    /*
     * Keep this template fail-closed.  The assignments below deliberately
     * document the exact current ads1299_platform_hal_t contract, so compiling
     * this file catches platform-interface drift.  Replace NULL with a pointer
     * to your board-owned LPSPI/GPIO context after completing the TODOs.
     */
    hal->user = NULL;
    hal->spi_transfer = board_spi_transfer;
    hal->pin_write = board_pin_write;
    hal->pin_read = board_pin_read;
    hal->delay_us = board_delay_us;

    /*
     * Before changing this return value to 0:
     *  1. configure LPSPI as CPOL=0, CPHA=1, MSB-first;
     *  2. configure CS/START/RESET/PWDN outputs and DRDY input;
     *  3. set hal->user to the board-owned peripheral/GPIO context;
     *  4. replace every TODO wrapper above with real MCUXpresso SDK calls;
     *  5. compile board_ads1299_binding_check.c in the same project.
     *
     * ADS1299 register/profile policy remains in firmware/core_driver/ads1299.
     */
    return -1;
}
