/*
 * MIMXRT1189 ADS1299 board binding template.
 *
 * Copy this file into the consuming MCUXpresso board project (or compile it
 * there after replacing the TODOs). Keep ADS1299 register programming out of
 * this file: this layer only binds board peripherals/pins to the portable
 * platform HAL.
 *
 * Validation status: TEMPLATE / PLANNED. This file intentionally contains no
 * invented MIMXRT1189-EVK pin numbers or SDK handles.
 */
#include "board_ads1299.h"

/*
 * Replace the functions below with thin wrappers around the MCUXpresso SDK
 * primitives selected/generated by your board project. The opaque ctx lets a
 * project keep its LPSPI/GPIO handles in one board-owned structure.
 */
static int board_spi_transfer(void *ctx, const unsigned char *tx,
                              unsigned char *rx, unsigned int len)
{
    (void)ctx;
    (void)tx;
    (void)rx;
    (void)len;
    /* TODO: blocking or bounded board-owned LPSPI transfer, Mode 1/MSB first. */
    return -1;
}

static void board_gpio_write(void *ctx, unsigned int pin, int level)
{
    (void)ctx;
    (void)pin;
    (void)level;
    /* TODO: route logical ADS1299 control pin to the generated GPIO API. */
}

static int board_gpio_read(void *ctx, unsigned int pin)
{
    (void)ctx;
    (void)pin;
    /* TODO: read DRDY; return its digital level. */
    return 1;
}

static void board_delay_us(void *ctx, unsigned int us)
{
    (void)ctx;
    (void)us;
    /* TODO: use the board/SDK microsecond delay primitive. */
}

int board_ads1299_hal(ads1299_platform_hal_t *hal)
{
    if (hal == 0) {
        return -1;
    }

    /*
     * TODO before returning success:
     *  1. configure LPSPI as CPOL=0, CPHA=1, MSB-first;
     *  2. configure CS/START/RESET/PWDN outputs and DRDY input;
     *  3. populate the board-owned context and pin identifiers expected by
     *     ads1299_platform_hal_t in ads1299_spi.h;
     *  4. assign the wrappers above to the matching HAL callback fields;
     *  5. verify board_ads1299_binding_check.c compiles in the same project.
     *
     * The exact structure fields are deliberately not guessed here: use the
     * current ads1299_platform_hal_t declaration as the compile-time contract.
     */
    (void)board_spi_transfer;
    (void)board_gpio_write;
    (void)board_gpio_read;
    (void)board_delay_us;

    return -1; /* fail closed until every board binding is intentionally set */
}
