CC ?= cc
CFLAGS ?= -std=c99 -Wall -Wextra -Werror -pedantic -O2

SELFTEST := ads1299_packet_selftest

.PHONY: all test clean

all: $(SELFTEST)

$(SELFTEST): ads1299_packet.c ads1299_packet.h ads1299_packet_selftest.c
	$(CC) $(CFLAGS) -I. ads1299_packet.c ads1299_packet_selftest.c -o $(SELFTEST)

test: $(SELFTEST)
	./$(SELFTEST)

clean:
	rm -f $(SELFTEST)
